name: VPN Dashboard CI/CD

on:
  push:
    branches: [ main, feature/enhanced-dashboard ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install boto3  # Explicitly install boto3
        
    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
        PYTHONWARNINGS: ignore::UserWarning
      run: |
        python -m pytest tests/ -v --disable-warnings
        
    - name: Build Docker image
      run: |
        docker build -t vpn-dashboard .

    - name: Run Docker container
      run: |
        docker run -d -p 4000:8050 vpn-dashboard
